backend:
  name: git-gateway
  branch: feat/decap

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "connections"
    label: "Connections"
    folder: "store/connections"
    create: true
    slug: "{{id}}"
    extension: "yml"
    format: "yaml"
    fields:
      # Campos Básicos
      - { label: "ID", name: "id", widget: "string", hint: "Identificador único (ex: mongodb, postgresql)" }
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { 
          label: "Categoria", 
          name: "category", 
          widget: "select", 
          options: ["databases", "container-platforms", "developer-consoles", "infrastructure-access", "network-services"]
        }
      - { label: "Nome do Ícone", name: "icon-name", widget: "string", hint: "Nome do ícone para exibição" }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "list", 
          allow_add: true,
          collapsed: false,
          field: { label: "Tag", name: "tag", widget: "string" }
        }
      - { label: "Novo", name: "isNew", widget: "boolean", default: false }

      # Overview Section
      - label: "Overview"
        name: "overview"
        widget: "object"
        collapsed: false
        fields:
          - { label: "Descrição Detalhada", name: "description", widget: "text", hint: "Descrição mais completa para a seção overview" }
          - { 
              label: "Features", 
              name: "features", 
              widget: "list", 
              allow_add: true,
              collapsed: true,
              field: { label: "Feature", name: "feature", widget: "string" }
            }
          - { 
              label: "Casos de Uso", 
              name: "useCases", 
              widget: "list", 
              allow_add: true,
              collapsed: true,
              field: { label: "Caso de Uso", name: "useCase", widget: "string" }
            }

      # Setup Guide Section
      - label: "Guia de Configuração"
        name: "setupGuide"
        widget: "object"
        collapsed: false
        fields:
          - label: "Métodos de Acesso"
            name: "accessMethods"
            widget: "object"
            fields:
              - { label: "Web App", name: "webapp", widget: "boolean", default: false }
              - { label: "CLI", name: "cli", widget: "boolean", default: false }
              - { label: "Runbooks", name: "runbooks", widget: "boolean", default: false }
          - { 
              label: "Requisitos", 
              name: "requirements", 
              widget: "list",
              allow_add: true,
              collapsed: false,
              field: { label: "Requisito", name: "requirement", widget: "string" }
            }

      # Advanced Configuration Section
      - label: "Configuração Avançada"
        name: "advancedConfiguration"
        widget: "object"
        collapsed: true
        fields:
          - { 
              label: "Connection String", 
              name: "connectionString", 
              widget: "text", 
              hint: "Exemplo de string de conexão com placeholders" 
            }
          - { 
              label: "Configurações de Features", 
              name: "featureConfiguration", 
              widget: "list",
              allow_add: true,
              collapsed: true,
              field: { label: "Configuração", name: "config", widget: "string" }
            }
          - { 
              label: "Outros Requisitos", 
              name: "otherRequirements", 
              widget: "list",
              allow_add: true,
              collapsed: true,
              field: { label: "Requisito", name: "requirement", widget: "string" }
            }
