backend:
  name: git-gateway
  branch: main
  publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "connections"
    label: "Connections"
    folder: "store/connections"
    create: true
    slug: "{{id}}"
    extension: "yml"
    format: "yaml"
    fields:
      - { label: "ID", name: "id", widget: "string", hint: "Unique identifier (e.g., mongodb, postgresql)" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { 
          label: "Category", 
          name: "category", 
          widget: "select", 
          options: ["databases", "container-platforms", "developer-consoles", "infrastructure-access", "network-services"]
        }
      - { label: "Icon Name", name: "icon-name", widget: "string", hint: "Icon name for display" }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "list", 
          allow_add: true,
          collapsed: false,
          field: { label: "Tag", name: "tag", widget: "string" }
        }
      - { label: "New", name: "isNew", widget: "boolean", default: false }

      # Overview Section
      - label: "Overview"
        name: "overview"
        widget: "object"
        collapsed: false
        fields:
          - { label: "Detailed Description", name: "description", widget: "text", hint: "More complete description for the overview section" }
          - { 
              label: "Features", 
              name: "features", 
              widget: "list", 
              allow_add: true,
              collapsed: true,
              field: { label: "Feature", name: "feature", widget: "string" }
            }
          - { 
              label: "Use Cases", 
              name: "useCases", 
              widget: "list", 
              allow_add: true,
              collapsed: true,
              field: { label: "Use Case", name: "useCase", widget: "string" }
            }

      # Setup Guide Section
      - label: "Setup Guide"
        name: "setupGuide"
        widget: "object"
        collapsed: false
        fields:
          - label: "Access Methods"
            name: "accessMethods"
            widget: "object"
            fields:
              - { label: "Web App", name: "webapp", widget: "boolean", default: false }
              - { label: "CLI", name: "cli", widget: "boolean", default: false }
              - { label: "Runbooks", name: "runbooks", widget: "boolean", default: false }
          - { 
              label: "Requirements", 
              name: "requirements", 
              widget: "list",
              allow_add: true,
              collapsed: false,
              field: { label: "Requirement", name: "requirement", widget: "string" }
            }

      # Advanced Configuration Section
      - label: "Advanced Configuration"
        name: "advancedConfiguration"
        widget: "object"
        collapsed: true
        fields:
          - { 
              label: "Connection String", 
              name: "connectionString", 
              widget: "text", 
              hint: "Connection string example with placeholders" 
            }
          - { 
              label: "Feature Configuration", 
              name: "featureConfiguration", 
              widget: "list",
              allow_add: true,
              collapsed: true,
              field: { label: "Configuration", name: "config", widget: "string" }
            }
          - { 
              label: "Other Requirements", 
              name: "otherRequirements", 
              widget: "list",
              allow_add: true,
              collapsed: true,
              field: { label: "Requirement", name: "requirement", widget: "string" }
            }
